# Generated by Django 6.0.5 on 2026-05-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actividad de salud',
                'verbose_name_plural': 'Actividades de salud',
                'db_table': 'actividad_salud',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('tipo_licencia', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible'), ('Licencia medica', 'Licencia médica'), ('Vacaciones', 'Vacaciones')], default='Disponible', max_length=30)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='UnidadSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad solicitante',
                'verbose_name_plural': 'Unidades solicitantes',
                'db_table': 'unidad_solicitante',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Camioneta', 'Camioneta'), ('Furgon', 'Furgón'), ('Ambulancia', 'Ambulancia'), ('Otro', 'Otro')], max_length=30)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Mantencion', 'Mantención'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='ReservaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movilesApp.actividadsalud')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movilesApp.conductor')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movilesApp.destino')),
                ('unidad_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movilesApp.unidadsolicitante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movilesApp.vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva de móvil',
                'verbose_name_plural': 'Reservas de móviles',
                'db_table': 'reserva_movil',
            },
        ),
    ]
