# Generated by Django 6.0.5 on 2026-05-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='tipo_licencia',
            field=models.CharField(choices=[('A1', 'A1 - Transporte de pasajeros'), ('A2', 'A2 - Taxi, ambulancia y transporte'), ('A3', 'A3 - Transporte remunerado de pasajeros'), ('A4', 'A4 - Transporte de carga'), ('A5', 'A5 - Vehículos articulados'), ('B', 'B - Vehículos particulares'), ('C', 'C - Motocicletas'), ('D', 'D - Maquinaria automotriz'), ('E', 'E - Vehículos de tracción animal'), ('F', 'F - Vehículos policiales y FF.AA.')], max_length=10),
        ),
    ]
